### ISSUE TITLE
migrate to ts

### ISSUE THREAD

**Issue by amilajack** [moshest/bidi-map#1]
would a pr to migrate this repo to ts be welcome?

**Comment by moshest** [comment]
Sure, thanks! 🙏

**Comment by amilajack** [comment]
I've realized the migration is more difficult than expected due to mocha. I've migrated and modernized this repo in my fork:
https://github.com/amilajack/bidi-map. Feel free to pick the pieces you find interesting.

**Comment by moshest** [comment]
Maybe can you just add the type definitions for now so we can release it with types?
